### ISSUE TITLE
Занятия 1 и 2.

### ISSUE THREAD

**Issue by stsdmchv** [fue-le-purp/Gunkin-A.V#2]
Проверь решения.

PS  если уж берете у кого-то задания, то берите правильные
![image](https://user-images.githubusercontent.com/7878715/136107544-8a378ad1-fa22-46ff-89de-1ba41976b32d.png)

**Comment by fue-le-purp** [comment]
Проверил, понял и осознал свою ошибку, сделал 8 задачу сам и всё заменил
